const submissions = [
  {
    id: 1,
    title: 'Yellow Pail',
    description: 'On-demand sand castle construction expertise.',
    url: '#',
    votes: 16,
    avatar: '../public/images/avatars/daniel.svg',
    submissionImage: '../public/images/detroit.svg',
  },
  {
    id: 2,
    title: 'Supermajority: The Fantasy Congress League',
    description: 'Earn points when your favorite politicians pass legislation',
    url: '#',
    votes: 11,
    avatar: '../public/images/avatars/carol.svg',
    submissionImage: '../public/images/burton.svg',
  },
  {
    id: 3,
    title: 'Tinfoild: Tailored tinfoil hats',
    description: 'We have your measurements and shipping address',
    url: '#',
    votes: 17,
    avatar: '../public/images/avatars/fred.svg',
    submissionImage: '../public/images/scientist.svg',
  },
  {
    id: 4,
    title: 'Haught or Naught',
    description: 'High-minded or absent-minded? You decide.',
    url: '#',
    votes: 17,
    avatar: '../public/images/avatars/mel.svg',
    submissionImage: '../public/images/midsummer.svg',
  },
  {
    id: 5,
    title: 'Golang and VueJs is a good thing ?',
    description: 'Maybe the most important thing that you will read today!',
    url: '#',
    votes: 19,
    avatar: '../public/images/avatars/mike.svg',
    submissionImage: '../public/images/viking.svg',
  },
];
